services:

  devcontainer:
    build:
      context: .
      dockerfile: golang.Dockerfile
      args:
        - GO_VERSION=1.23.1
        - TINYGO_VERSION=0.33.0
        - USER_NAME=${USER}
    volumes:
      - ../..:/workspaces:cached      
    environment:
      - MESSAGE="Hello World!"
    command: sleep infinity

